### ISSUE TITLE
Feature matching loss values

### ISSUE THREAD

**Issue by guiandrade2** [etaoxing/semi-supervised-gan#1]
While using the feature matching loss GAN on another datasets, I verify that the feature matching loss achieves very small values, yet the discriminator can still distinguish between real and fake images for the big majority of cases. Is this expected? Is this a problem? Is it a desired effect?

**Comment by etaoxing** [comment]
Hi, thanks for the interest in this codebase. As a disclaimer, I haven't looked at this in a couple years.

From the original improved GAN [paper](https://arxiv.org/pdf/1606.03498.pdf#page=3), Section 3.2:
> Interestingly, however, feature matching was found to work much better if the goal is to obtain a strong classifier using the approach to semi-supervised learning described in Section 5.

This project trains a GAN for classification. We want the classifier (discriminator of the GAN) to be good, so it can distinguish b/w the different classes (including the added "fake" class). You can check out Section 4 of this [paper](https://arxiv.org/pdf/1707.02796.pdf#page=4) for more details on an application of this approach.

I'm not sure about your specific use case, but that is an expected result for the implementation in this codebase.

**Comment by guiandrade2** [comment]
Thank you for the answer, I would like to ask as well, is there any resource regarding architectures of generators for GAN systems? I am having a lot of trouble finding something solid about it. 

Thank you for your time

**Comment by etaoxing** [comment]
[Image generation](https://paperswithcode.com/task/image-generation) is probably a better direction for training generators.
